# **Dataset Details**

In [1]:
import numpy as np
from src.data.pmlb import load_pmlb_dataset

# **Classification**

## **Churn**

In [3]:
X, y = load_pmlb_dataset("churn", local_cache_dir="../data/classification/")

print(f"Dataset shape: {X.shape}")
print(f"N. classes   : {len(np.unique(y))}")

Dataset shape: (5000, 20)
N. classes   : 2


In [4]:
X

array([[ 16.  , 128.  , 415.  , ...,   3.  ,   2.7 ,   1.  ],
       [ 35.  , 107.  , 415.  , ...,   3.  ,   3.7 ,   1.  ],
       [ 31.  , 137.  , 415.  , ...,   5.  ,   3.29,   0.  ],
       ...,
       [  7.  ,  61.  , 415.  , ...,   4.  ,   3.67,   1.  ],
       [  7.  , 109.  , 510.  , ...,   6.  ,   2.3 ,   0.  ],
       [ 46.  ,  86.  , 415.  , ...,  16.  ,   2.51,   0.  ]],
      shape=(5000, 20))

In [5]:
np.unique(y, return_counts=True)[-1] / y.shape[0]

array([0.8586, 0.1414])

## **Wave Form**

In [6]:
X, y = load_pmlb_dataset("waveform_21", local_cache_dir="../data/classification/")

print(f"Dataset shape: {X.shape}")
print(f"N. classes   : {len(np.unique(y))}")

Dataset shape: (5000, 21)
N. classes   : 3


In [7]:
X

array([[-1.23, -1.56, -1.75, ...,  1.2 ,  0.24, -0.56],
       [-0.69,  2.43,  0.61, ...,  1.78,  0.6 ,  2.42],
       [-0.12, -0.94,  1.29, ..., -0.01, -0.79, -0.12],
       ...,
       [ 0.01, -1.99,  0.16, ...,  1.  ,  1.21, -0.27],
       [-0.4 ,  0.41, -0.48, ...,  2.08,  1.31,  1.37],
       [ 0.63, -0.07,  2.71, ...,  0.09,  0.01,  0.6 ]], shape=(5000, 21))

In [8]:
np.unique(y, return_counts=True)[-1] / y.shape[0]

array([0.3314, 0.3294, 0.3392])

# **Regression**

## **529_pollen**

In [9]:
X, y = load_pmlb_dataset("529_pollen", local_cache_dir="../data/regression/")

print(f"Dataset shape: {X.shape}")
print(f"Mean target  : {np.mean(y):.2f}")
print(f"Std target   : {np.std(y):.2f}")

Dataset shape: (3848, 4)
Mean target  : 0.00
Std target   : 3.14


In [10]:
X

array([[ -2.34820008,   3.63140011,   5.02890015,  10.87209988],
       [ -1.15199995,   1.48049998,   3.23749995,  -0.59390002],
       [ -2.52449989,  -6.86329985,  -2.80369997,   8.46310043],
       ...,
       [  6.38140011,   4.36479998, -22.42289925, -19.13339996],
       [  2.70140004,  -3.87590003,  -7.26270008,  -6.2986002 ],
       [  6.62820005,  -0.76840001, -10.63129997,  -5.9355998 ]],
      shape=(3848, 4))

In [12]:
np.mean(X, axis=0)

array([-0.00363664,  0.00015967,  0.00310312,  0.00423703])

In [13]:
np.std(X, axis=0)

array([ 6.39740514,  5.18563661,  7.87417548, 10.04178659])